<?php

namespace ApiBundle\Repository;

/**
 * PushKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
